### ISSUE TITLE
Action summary on pull request comment section

### ISSUE THREAD

**Issue by NunesMig** [advanced-security/secret-scanning-review-action#2]
Hello, 

First of all thank you for sharing this action with us in the marketplace, it is very useful.

I'd like to ask you if it would be in your roadmap for this action to create an option or feature that would publish the action summary in the respective pull request comment section.

Thank you for your time. 

Best regards,

Miguel

**Comment by felickz** [comment]
Thanks for the feedback, has been on my todo list to add this -  https://github.com/advanced-security/secret-scanning-review-action/blob/9ac335386345f91c4610dae584d6410e5631e04d/action.ps1#L55
