### ISSUE TITLE
Feature Request: Suppress empty PR Comments 

### ISSUE THREAD

**Issue by luca-regne** [advanced-security/secret-scanning-review-action#28]
Add an option to suppress PR comments when no secrets are found.

**Comment by gabrielss4ntos** [comment]
This would be a very useful feature, to make a comment on the PR only if a secret is found.

**Comment by felickz** [comment]
I was following the paradigm of `dependency-review` 


![Image](https://github.com/user-attachments/assets/cf844dd6-73ce-409b-a02d-c6a277770524)



But i agree this is too noisy - you can go visit the action run summary to see the report (that says nothing 😆 ) so i will suppress this scenario as requested in `1.1`
